server:
  port: 80
spring:
  cloud:
    gateway:
      discovery:
        locator:
          ###允许通过注册中心获取地址调用
          enabled: true
#          filters:
#            - StripPrefix=1
      ###路由策略
      routes:
        ###根据我们的服务名称查找地址实现调用
        - id: member
          uri: lb://member/
          predicates:
            - Path=/member/**
        - id: order
          uri: lb://order/
          predicates:
            - Path=/order/**

#        - id: weight_order
#          uri: lb://order
#          predicates:
#              - Weight=group1,2
#        - id: weight_member
#          uri: lb://member
#          predicates:
#              - Weight=group1,1
